sudo: false
language: java
jdk:
- oraclejdk8
script:
- test/run.sh
notifications:
  slack:
    secure: Q1BghE2l8ObVqw6ehUozBATpdwhTFRHg3zZPqeMf9alR5O+g7GT3JvYbZpapNygUbVWhi4l2zrN1Sp91Eqr8IbsGxYbKwN27if45VmvoXWwN0y0s2UKuCBfTJDvcXskbUn8wKdwR3LrH95ji+GYT5Gh5clC3G3q6HkeYffcTeX4=
env:
  global:
  - secure: FT6/wRYEWG5K1b48W+HO2gtPXJ59Oed3igc6pBIJojPV9WYDymTRP8e/zc6sKeDHN4SXM35ls3sdXaTHKP0sX7rZMRHtDdgrmWMMNsOsk3UoerkLjrfkr3uLkY6oM4mgiS1kLov2MDeiUAudbSxP6qx75v/RFFOoymeyQlXuJiA=
  - secure: BW+8fUbrEIzlmoJUOrtbgNYJKh7Rp42exQOyC+7DWtGvDfJmDrE7unht/rjWEjsLKiB7gAG9ZFX4oMzMmJ/KQxic5qfW8ztcbRvDuFTo5iqF+mZKGxVstgKSZ/OrEOCLZ3Gmqa/7dcS2VnGy9KdWwDKlglm7pc5SavQzThvYhG8=
